org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
loader_version=0.19.3
mappings_version=2024.11.17

mod_version=2.1.4+Fabric1.21.1
mod_id=poopsky
maven_group=com.altnoir.poopsky
archive_name=poopsky

fabric_api_version=0.116.15+1.21.1

registrate_version=1.3.34-MC1.21.1
configapi_version=21.1.6
kuma_version=21.0.8+1.21

farmersdelight_version=1.21.1-3.3.3
touhoulittlemaid_version=0.8.2-neo1.5.3+mc1.21.1
sable_companion_version=1.6.0

recipeviewer=jei
jei_version=19.44.0.401
