@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.altnoir.poopsky.content.entity.renderer;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;